<?php

declare(strict_types=1);

namespace DrevOps\Eddy\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Component\Yaml\Yaml;

/**
 * Tests the Composer cache of the test workflow.
 *
 * A cache path that Composer never writes to, or a key that hashes files a
 * fresh checkout lacks, makes the cache restore and save nothing.
 *
 * A step output read before the step that sets it resolves to an empty
 * string. The job passes in each case, so neither a linter nor a run reports
 * it.
 *
 * phpcs:disable Drupal.Commenting.FunctionComment.Missing
 * phpcs:disable Drupal.Commenting.DocComment.MissingShort
 */
#[Group('p0')]
final class WorkflowsComposerCacheTest extends UnitTestCase {

  protected const string CACHE_STEP = 'Cache Composer dependencies';

  /**
   * The first step that runs Composer.
   */
  protected const string INSTALL_STEP = 'Install the tooling';

  protected const string DIRECTORY_COMMAND = 'composer config cache-files-dir';

  protected const string LEG = '${{ matrix.name }}';

  /**
   * A project generated by 'init.php', as recorded by the init snapshot.
   */
  protected const string GENERATED_PROJECT = '.eddy/tests/fixtures/init/_baseline';

  #[DataProvider('dataProviderPathIsComposerArchiveDirectory')]
  public function testPathIsComposerArchiveDirectory(string $job): void {
    $path = self::cacheInput($job, 'path');

    $this->assertMatchesRegularExpression('/^\$\{\{\s*steps\.[\w-]+\.outputs\.[\w-]+\s*\}\}$/', $path, sprintf('The "%s" step of the %s job caches "%s". Only a step output can name the directory Composer writes archives to on the runner.', self::CACHE_STEP, $job, $path));

    $command = self::outputs($job)[self::references($path)[0] ?? '']['command'] ?? NULL;

    $this->assertSame(self::DIRECTORY_COMMAND, $command, sprintf('The "%s" step of the %s job must cache the directory that "%s" reports.', self::CACHE_STEP, $job, self::DIRECTORY_COMMAND));
  }

  public static function dataProviderPathIsComposerArchiveDirectory(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderCacheIsRestoredBeforeComposerRuns')]
  public function testCacheIsRestoredBeforeComposerRuns(string $job): void {
    $this->assertLessThan(self::stepIndex($job, self::INSTALL_STEP), self::stepIndex($job, self::CACHE_STEP), sprintf('The "%s" step of the %s job must restore the cache before "%s" runs Composer.', self::CACHE_STEP, $job, self::INSTALL_STEP));
  }

  public static function dataProviderCacheIsRestoredBeforeComposerRuns(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderInputsReadEarlierOutputs')]
  public function testInputsReadEarlierOutputs(string $job): void {
    $cache = self::stepIndex($job, self::CACHE_STEP);
    $outputs = self::outputs($job);
    $unset = [];

    foreach (self::cacheInputs($job) as $value) {
      foreach (self::references($value) as $reference) {
        if (($outputs[$reference]['step'] ?? $cache) >= $cache) {
          $unset[] = $reference;
        }
      }
    }

    $this->assertSame([], $unset, sprintf('The "%s" step of the %s job reads outputs that no earlier step sets, so each resolves to an empty string: %s', self::CACHE_STEP, $job, implode(', ', $unset)));
  }

  public static function dataProviderInputsReadEarlierOutputs(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderKeyHashesFilesOfGeneratedProject')]
  public function testKeyHashesFilesOfGeneratedProject(string $job): void {
    $files = self::hashedFiles(self::cacheInput($job, 'key'));

    $this->assertNotSame([], $files, sprintf('The key of the "%s" step of the %s job hashes no files, so a change to the Composer manifests saves no new cache.', self::CACHE_STEP, $job));

    foreach ($files as $file) {
      $this->assertDoesNotMatchRegularExpression('/[*?\[]/', $file, sprintf('The key of the "%s" step of the %s job hashes the pattern "%s". A pattern that matches nothing in a fresh checkout leaves the key constant, so name each file.', self::CACHE_STEP, $job, $file));
      $this->assertFileExists(self::rootDir() . '/' . self::GENERATED_PROJECT . '/' . $file, sprintf('The key of the "%s" step of the %s job hashes "%s", which a freshly generated project does not have.', self::CACHE_STEP, $job, $file));
    }
  }

  public static function dataProviderKeyHashesFilesOfGeneratedProject(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderKeySeparatesMatrixLegs')]
  public function testKeySeparatesMatrixLegs(string $job): void {
    $this->assertStringContainsString(self::LEG, self::cacheInput($job, 'key'), sprintf('The key of the "%s" step of the %s job must hold %s. The matrix legs need different packages, and legs that share a key race to save 1 cache.', self::CACHE_STEP, $job, self::LEG));
  }

  public static function dataProviderKeySeparatesMatrixLegs(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderKeyHoldsDate')]
  public function testKeyHoldsDate(string $job): void {
    $outputs = self::outputs($job);
    $dates = array_filter(self::references(self::cacheInput($job, 'key')), static fn(string $reference): bool => str_starts_with($outputs[$reference]['command'] ?? '', 'date '));

    $this->assertNotSame([], $dates, sprintf('The key of the "%s" step of the %s job must hold a date that an earlier step computes. Builds resolve without a lock file and an existing key never saves again, so without a date the cache keeps the archives of its first run.', self::CACHE_STEP, $job));
  }

  public static function dataProviderKeyHoldsDate(): \Iterator {
    yield from self::composerJobs();
  }

  #[DataProvider('dataProviderRestoreKeysMatchSameLeg')]
  public function testRestoreKeysMatchSameLeg(string $job): void {
    $key = self::cacheInput($job, 'key');
    $restore_keys = array_filter(array_map(trim(...), explode("\n", self::cacheInput($job, 'restore-keys'))));

    $this->assertNotSame([], $restore_keys, sprintf('The "%s" step of the %s job has no restore keys, so a new key starts from an empty cache.', self::CACHE_STEP, $job));

    foreach ($restore_keys as $restore_key) {
      $this->assertStringStartsWith($restore_key, $key, sprintf('The restore key "%s" of the %s job is not a prefix of its key, so it never matches a cache that the job saved.', $restore_key, $job));
      $this->assertStringContainsString(self::LEG, $restore_key, sprintf('The restore key "%s" of the %s job must hold %s, otherwise a miss restores the cache of another matrix leg.', $restore_key, $job, self::LEG));
    }
  }

  public static function dataProviderRestoreKeysMatchSameLeg(): \Iterator {
    yield from self::composerJobs();
  }

  /**
   * List the jobs that run Composer.
   *
   * @return \Iterator<string, array{job: string}>
   *   The job names, keyed by job name.
   */
  protected static function composerJobs(): \Iterator {
    foreach (array_keys(self::jobs()) as $job) {
      $names = array_column(self::steps((string) $job), 'name');

      if (in_array(self::INSTALL_STEP, $names, TRUE)) {
        yield (string) $job => ['job' => (string) $job];
      }
    }
  }

  /**
   * Read the jobs of the test workflow.
   *
   * @return array<mixed, mixed>
   *   The job definitions, keyed by job name.
   */
  protected static function jobs(): array {
    $path = self::rootDir() . '/.github/workflows/test.yml';
    $contents = file_get_contents($path);

    if ($contents === FALSE) {
      self::fail(sprintf('Unable to read %s.', $path));
    }

    $parsed = Yaml::parse($contents);
    $jobs = is_array($parsed) ? ($parsed['jobs'] ?? NULL) : NULL;

    if (!is_array($jobs)) {
      self::fail(sprintf('%s declares no jobs.', basename($path)));
    }

    return $jobs;
  }

  /**
   * Read the steps of a job.
   *
   * @param string $job
   *   Name of the job.
   *
   * @return array<int, array<mixed, mixed>>
   *   The step definitions, in order.
   */
  protected static function steps(string $job): array {
    $definition = self::jobs()[$job] ?? NULL;
    $steps = is_array($definition) ? ($definition['steps'] ?? NULL) : NULL;

    if (!is_array($steps)) {
      self::fail(sprintf('The %s job declares no steps.', $job));
    }

    return array_values(array_filter($steps, is_array(...)));
  }

  /**
   * Find the position of a named step in a job.
   *
   * @param string $job
   *   Name of the job.
   * @param string $name
   *   Name of the step.
   *
   * @return int
   *   The index of the step.
   */
  protected static function stepIndex(string $job, string $name): int {
    foreach (self::steps($job) as $index => $step) {
      if (($step['name'] ?? NULL) === $name) {
        return $index;
      }
    }

    self::fail(sprintf('The %s job has no "%s" step.', $job, $name));
  }

  /**
   * Read the string inputs of the cache step of a job.
   *
   * @param string $job
   *   Name of the job.
   *
   * @return array<string, string>
   *   The inputs, keyed by input name.
   */
  protected static function cacheInputs(string $job): array {
    $with = self::steps($job)[self::stepIndex($job, self::CACHE_STEP)]['with'] ?? NULL;

    if (!is_array($with)) {
      self::fail(sprintf('The "%s" step of the %s job has no inputs.', self::CACHE_STEP, $job));
    }

    $inputs = [];

    foreach ($with as $input => $value) {
      if (is_string($input) && is_string($value)) {
        $inputs[$input] = $value;
      }
    }

    return $inputs;
  }

  /**
   * Read an input of the cache step of a job.
   *
   * @param string $job
   *   Name of the job.
   * @param string $input
   *   Name of the input.
   *
   * @return string
   *   The input value.
   */
  protected static function cacheInput(string $job, string $input): string {
    $value = self::cacheInputs($job)[$input] ?? NULL;

    if ($value === NULL) {
      self::fail(sprintf('The "%s" step of the %s job has no "%s" input.', self::CACHE_STEP, $job, $input));
    }

    return $value;
  }

  /**
   * Find the step outputs that a job sets from a command substitution.
   *
   * @param string $job
   *   Name of the job.
   *
   * @return array<string, array{step: int, command: string}>
   *   The index of the setting step and the substituted command, keyed by the
   *   expression that reads the output, such as 'steps.cache.outputs.dir'.
   */
  protected static function outputs(string $job): array {
    $outputs = [];

    foreach (self::steps($job) as $index => $step) {
      $id = $step['id'] ?? NULL;
      $run = $step['run'] ?? NULL;

      if (!is_string($id)) {
        continue;
      }

      if (!is_string($run)) {
        continue;
      }

      if (!str_contains($run, 'GITHUB_OUTPUT')) {
        continue;
      }

      preg_match_all('/\b([\w-]+)=\$\((.+?)\)/', $run, $matches, PREG_SET_ORDER);

      foreach ($matches as $match) {
        $outputs['steps.' . $id . '.outputs.' . $match[1]] = ['step' => $index, 'command' => $match[2]];
      }
    }

    return $outputs;
  }

  /**
   * Find the step outputs that an expression reads.
   *
   * @param string $value
   *   The input value holding the expressions.
   *
   * @return array<int, string>
   *   The references, such as 'steps.cache.outputs.dir'.
   */
  protected static function references(string $value): array {
    preg_match_all('/\bsteps\.[\w-]+\.outputs\.[\w-]+/', $value, $matches);

    return $matches[0];
  }

  /**
   * Find the arguments of every 'hashFiles()' call in a key.
   *
   * @param string $key
   *   The cache key.
   *
   * @return array<int, string>
   *   The paths and patterns passed to 'hashFiles()'.
   */
  protected static function hashedFiles(string $key): array {
    preg_match_all('/hashFiles\(([^)]*)\)/', $key, $calls);
    preg_match_all("/'([^']*)'/", implode(' ', $calls[1]), $arguments);

    return $arguments[1];
  }

  protected static function rootDir(): string {
    return dirname(__DIR__, 4);
  }

}
